<div id="sticky">
    <span id="sticky-fb" data-social-link="https://www.facebook.com/BACKSTAGEmakeupGmbH"></span>
    <span id="sticky-pinterest" data-social-link="https://www.pinterest.com/backstagemakeup"></span>
    <span id="sticky-instagram" data-social-link="https://instagram.com/backstagemakeup_hh/"></span>
    <hr>
    <span id="sticky-trustedshop" data-social-link="http://www.trustedshops.de/"></span>
    <span id="sticky-kontakt" data-social-link="/kontakt.html"></span>
</div>